### Reference:
https://personal.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/#examples

In [ ]:
#### The operation performed on Gaussian elimination
ii. Multiply all the elements in any one row of the matrix by a non-zero scalar.
iii. Add a scalar multiple of any one row to another row.

In [2]:
import numpy as np

In [3]:
def add_row(A,k,i,j):
    "Add k times row j to row i in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [4]:
def scale_row(A,k,i):
    "Multiply row i by k in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [5]:
import numpy as np
np.set_printoptions(suppress=True)

### ===============================
### Example 1:
### ===============================

In [45]:
A = np.array([[1,1,70],[24,14,1180]])
print(A)

[[   1    1   70]
 [  24   14 1180]]


In [46]:
k = -24
j = 0
i = 1
A1 = add_row(A,k,i,j)
print(A1)

[[   1.    1.   70.]
 [   0.  -10. -500.]]


In [47]:
k = -1/10
i = 1
A2 = scale_row(A1,k,i)
print(A2)

[[ 1.  1. 70.]
 [ 0.  1. 50.]]


In [48]:
k = -1
j = 1
i = 0
A3 = add_row(A2,k,i,j)
print(A3)

[[ 1.  0. 20.]
 [ 0.  1. 50.]]


In [49]:
B = np.array([[3,-5,5],[7,1,37]])
print(B)

[[ 3 -5  5]
 [ 7  1 37]]


In [50]:
k = 1/3
i = 0
B1 = scale_row(B,k,i)
print(B1)

[[ 1.         -1.66666667  1.66666667]
 [ 7.          1.         37.        ]]


In [51]:
k = -7
j = 0
i = 1
B2 = add_row(B1,k,i,j)
print(B2)

[[ 1.         -1.66666667  1.66666667]
 [ 0.         12.66666667 25.33333333]]


In [52]:
k = 1/12.66666667
i = 1
B3 = scale_row(B2,k,i)
print(B3)

[[ 1.         -1.66666667  1.66666667]
 [ 0.          1.          2.        ]]


In [53]:
k = 1.66666667
j = 1
i = 0
B4 = add_row(B3,k,i,j)
print(B4)

[[1.         0.         5.00000001]
 [0.         1.         2.        ]]


### ===============================
### Example 2:
### ===============================

In [54]:
P = np.array([[-1, 2, -3, 1, 0, 0],[2, 1, 0, 0 , 1, 0],[4, -2, 5, 0, 0, 1]])
P

array([[-1,  2, -3,  1,  0,  0],
       [ 2,  1,  0,  0,  1,  0],
       [ 4, -2,  5,  0,  0,  1]])

In [55]:
k = -1
i = 0
P1 = scale_row(P,k,i)
print(P1)

[[ 1. -2.  3. -1.  0.  0.]
 [ 2.  1.  0.  0.  1.  0.]
 [ 4. -2.  5.  0.  0.  1.]]


In [56]:
k = -2
j = 0
i = 1
P2 = add_row(P1,k,i,j)
print(P2)

[[ 1. -2.  3. -1.  0.  0.]
 [ 0.  5. -6.  2.  1.  0.]
 [ 4. -2.  5.  0.  0.  1.]]


In [57]:
k = 1/5
i = 1
P3 = scale_row(P2,k,i)
print(P3)

[[ 1.  -2.   3.  -1.   0.   0. ]
 [ 0.   1.  -1.2  0.4  0.2  0. ]
 [ 4.  -2.   5.   0.   0.   1. ]]


In [58]:
k = 2
j = 1
i = 0
P4 = add_row(P3,k,i,j)
print(P4)

[[ 1.   0.   0.6 -0.2  0.4  0. ]
 [ 0.   1.  -1.2  0.4  0.2  0. ]
 [ 4.  -2.   5.   0.   0.   1. ]]


In [59]:
k = -4
j = 0
i = 2
P5 = add_row(P4,k,i,j)
print(P5)

[[ 1.   0.   0.6 -0.2  0.4  0. ]
 [ 0.   1.  -1.2  0.4  0.2  0. ]
 [ 0.  -2.   2.6  0.8 -1.6  1. ]]


In [60]:
k = 2
j = 1
i = 2
P6 = add_row(P5,k,i,j)
print(P6)

[[ 1.   0.   0.6 -0.2  0.4  0. ]
 [ 0.   1.  -1.2  0.4  0.2  0. ]
 [ 0.   0.   0.2  1.6 -1.2  1. ]]


In [61]:
k = 1/0.2
i = 2
P7 = scale_row(P6,k,i)
print(P7)

[[ 1.   0.   0.6 -0.2  0.4  0. ]
 [ 0.   1.  -1.2  0.4  0.2  0. ]
 [ 0.   0.   1.   8.  -6.   5. ]]


In [62]:
k = 1.2
j = 2
i = 1
P8 = add_row(P7,k,i,j)
print(P8)

[[ 1.   0.   0.6 -0.2  0.4  0. ]
 [ 0.   1.   0.  10.  -7.   6. ]
 [ 0.   0.   1.   8.  -6.   5. ]]


In [63]:
k = -0.6
j = 2
i = 0
P9 = add_row(P8,k,i,j)
print(P9)

[[ 1.  0. -0. -5.  4. -3.]
 [ 0.  1.  0. 10. -7.  6.]
 [ 0.  0.  1.  8. -6.  5.]]


### ===========================================
### Gaussian Elimination Algorithm in Python
### ===========================================

In [64]:
def gauss_method(aug_mat):
    # num of rows/unknown variables
    n_row,n_col = aug_mat.shape
    for i in range(n_row):
            
        divisor = aug_mat[i,i]
        for j in range(n_col):
            aug_mat[i,j] /= divisor
            
        for j in range(n_row):
            if j != i:
                multiplier = -aug_mat[j,i]
                aug_mat[j,:] += multiplier*aug_mat[i,:]
    return aug_mat

In [65]:
import numpy as np
a = np.array([[2,-3,  1],
              [7, 9, -3],
              [6, 7,  2]], dtype = float)

b = np.array([[-22], [14], [91]], dtype = float)

aug_mat = np.hstack([a,b])

print(gauss_method(aug_mat))

[[ 1.  0.  0. -4.]
 [ 0.  1.  0. 11.]
 [ 0.  0.  1. 19.]]
