In [3]:
A = [[2,4,3],[4,-1,2]]

In [4]:
B = [[5,3],[2,2],[6,5]]

#### Method 1: Using nested for loops
In this program, we have used nested for loops for computation of result which will iterate through each row and column of the matrices, at last it will accumulate the sum of product in the result.

In [7]:
n = len(A) 
m = len(B)
p = len(B[0])

In [14]:
res = [[0 for x in range(n)] for y in range(p)]

In [15]:
res

[[0, 0], [0, 0]]

In [16]:
for i in range(n):
    for j in range(p):
        for k in range(m):
            res[i][j] += A[i][k]*B[k][j]

In [13]:
for r in res:
    print(r)

[36, 29]
[30, 20]


#### Method 2: Using numpy
Multiplication using Numpy also know as vectorization which main aim to reduce or remove the explicit use of for loops in the program by which computation becomes faster.

Numpy is a build in a package in python for array-processing and manipulation.For larger matrix operations we use numpy python package which is 1000 times faster than iterative one method.

NumPy is a Python library. <br>
NumPy is used for working with arrays. <br>
NumPy is short for "Numerical Python". <br>

In [23]:
import numpy as np

A1 = np.array([[2,4,3],[4,-1,2]])
B1 = np.array([[5,3],[2,2],[6,5]])
print(A1)
print("=================")
print(B1)

[[ 2  4  3]
 [ 4 -1  2]]
[[5 3]
 [2 2]
 [6 5]]


In [25]:
np.matmul(A1, B1)

array([[36, 29],
       [30, 20]])

In [26]:
import numpy as np
a = np.array([[1, 0],
              [0, 1]])

In [27]:
b = np.array([[4, 1],
              [2, 2]])

In [28]:
x = np.matmul(a, b)

In [29]:
x

array([[4, 1],
       [2, 2]])

In [128]:
a = np.array([[1,4],[6,-2]])
b = np.array([[3,6],[3,4]])

In [131]:
np.matmul(a,b)

array([[15, 22],
       [12, 28]])

In [132]:
np.matmul(b,a)

array([[39,  0],
       [27,  4]])

In [30]:
A1

array([[ 2,  4,  3],
       [ 4, -1,  2]])

In [31]:
A1t = np.transpose(A1)
A1t

array([[ 2,  4],
       [ 4, -1],
       [ 3,  2]])

In [116]:
B1t = np.transpose(B1)

In [36]:
A = np.array([[1,7],[-3,4],[5,6]])
A

array([[ 1,  7],
       [-3,  4],
       [ 5,  6]])

In [37]:
B = np.array([[4,0],[9,2],[-1,4]])
B

array([[ 4,  0],
       [ 9,  2],
       [-1,  4]])

In [38]:
r = 2

In [39]:
r*A + B

array([[ 6, 14],
       [ 3, 10],
       [ 9, 16]])

In [42]:
A2 = np.array([[1,4],[6,-2]]) 
A2

array([[ 1,  4],
       [ 6, -2]])

In [43]:
B2 = np.array([[3,6],[3,4]])
B2

array([[3, 6],
       [3, 4]])

In [44]:
np.matmul(A2,B2)

array([[15, 22],
       [12, 28]])

In [45]:
np.matmul(B2,A2)

array([[39,  0],
       [27,  4]])