####  Matric multiplication Using numpy
Multiplication using Numpy also know as vectorization which main aim to reduce or remove the explicit use of for loops in the program by which computation becomes faster.

Numpy is a build in a package in python for array-processing and manipulation.For larger matrix operations we use numpy python package which is 1000 times faster than iterative one method.

NumPy is a Python library. <br>
NumPy is used for working with arrays. <br>
NumPy is short for "Numerical Python". <br>

In [44]:
import numpy as np

A1 = np.array([[2,4,3],[4,-1,2]])
B1 = np.array([[5,3],[2,2],[6,5]])
print(A1)
print("=================")
print(B1)

[[ 2  4  3]
 [ 4 -1  2]]
[[5 3]
 [2 2]
 [6 5]]


In [45]:
np.matmul(A1, B1)

array([[36, 29],
       [30, 20]])

In [46]:
import numpy as np
a = np.array([[1, 0],
              [0, 1]])

In [47]:
b = np.array([[4, 1],
              [2, 2]])

In [48]:
x = np.matmul(a, b)

In [49]:
x

array([[4, 1],
       [2, 2]])

In [50]:
a = np.array([[1,4],[6,-2]])
b = np.array([[3,6],[3,4]])

In [51]:
np.matmul(a,b)

array([[15, 22],
       [12, 28]])

In [52]:
np.matmul(b,a)

array([[39,  0],
       [27,  4]])

In [53]:
A1

array([[ 2,  4,  3],
       [ 4, -1,  2]])

In [54]:
A1t = np.transpose(A1)
A1t

array([[ 2,  4],
       [ 4, -1],
       [ 3,  2]])

In [55]:
B1t = np.transpose(B1)

In [56]:
A = np.array([[1,7],[-3,4],[5,6]])
A

array([[ 1,  7],
       [-3,  4],
       [ 5,  6]])

In [57]:
B = np.array([[4,0],[9,2],[-1,4]])
B

array([[ 4,  0],
       [ 9,  2],
       [-1,  4]])

In [58]:
r = 2

In [59]:
r*A + B

array([[ 6, 14],
       [ 3, 10],
       [ 9, 16]])

In [60]:
A2 = np.array([[1,4],[6,-2]]) 
A2

array([[ 1,  4],
       [ 6, -2]])

In [61]:
B2 = np.array([[3,6],[3,4]])
B2

array([[3, 6],
       [3, 4]])

In [62]:
np.matmul(A2,B2)

array([[15, 22],
       [12, 28]])

In [63]:
np.matmul(B2,A2)

array([[39,  0],
       [27,  4]])